import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Market from "../components/svg/home/market";
import Restaurant from "../components/svg/home/restaurant";
import FastFood from "../components/svg/home/fast-food";
import HomeLogo from "../components/svg/home/logo";
import BigRetail from "../components/svg/home/big-retail";
import HomeDecor from "../components/svg/home/home-decor";
import MediumRetail from "../components/svg/home/medium-retail";
import PopUpMessenger from '../components/common/popup-messenger'
import arriw__down from '../public/static/home/close-button.png' 
import { motion } from "framer-motion";

const HomeLogoIcon = () => (
  <div>
    <HomeLogo width={109} height={57} />
  </div>
);

const MarketIcon = () => (
  <div>
    <Market width={94} height={80} />
  </div>
);

const RestaurantIcon = () => <Restaurant width={94} height={80} />

const FastFoodIcon = () => (
  <div>
    <FastFood width={94} height={80} />
  </div>
);

const BigRetailIcon = () => (
  <div>
    <BigRetail width={94} height={80} />
  </div>
);

const HomeDecorIcon = () => (
  <div>
    <HomeDecor width={94} height={80} />
  </div>
);

const MediumRetailIcon = () => (
  <div>
    <MediumRetail width={94} height={80} />
  </div>
);

const nav__items = [
  { path: "/market", icon: <MarketIcon />, title: "supermarket" },
  { path: "/restaurant", icon: <RestaurantIcon />, title: "restaurant" },
  { path: "/fast-food", icon: <FastFoodIcon />, title: "fast-food" },
  { path: "/big-retail", icon: <BigRetailIcon />, title: "big retail" },
  { path: "/home-decor", icon: <HomeDecorIcon />, title: "home decor" },
  {
    path: "/medium-retail",
    icon: <MediumRetailIcon />,
    title: "medium retail",
  },
];

export default function Home() {
  const [isVisible, setIsVisible] = React.useState(false);

  React.useEffect(() => {
    setTimeout(() => {
      setIsVisible(true);
    }, 5000);
  }, []);
  return (
    <>
      <Head>
        <title>Newton Park</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.section
        className={styles.home}
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        transition={{ duration: 0.3 }}
      >
        <div className={styles.home__bg}>
          <div className={styles.home__shadow}></div>

          <header className={styles.header}>
            <div className={styles.header__wrapper}>
              <div className={styles.logo}>
                <HomeLogoIcon />
              </div>
            </div>
          </header>
        </div>
        <div className={styles.container}>
          <div className={styles.inner}>
            <div className={styles.content}>
              <h1 className={styles.title}>SPAȚII COMERCIALE </h1>
              <p className={styles.NP__decor_title}>NEWTON PARK</p>
              <p className={styles.subtitle}>Proeminente și fără replică</p>
            </div>

            <div className={styles.form__inner}>
              <h2 className={styles.form__title}>
                Solicită prezentarea
                <br />
                <span className={styles.NP__decor_form}>NEWTON PARK</span> PDF
              </h2>
              <form className={styles.form}>
                <input type="email" placeholder="Adresa de email" />
                <input type="tel" placeholder="Numărul de telefon" />
                <button className={styles.form__button}>
                  Solicită prezentarea
                </button>
              </form>
            </div>
          </div>

          <div className={styles.nav__inner}>
            <div className={styles.nav__items}>
              {nav__items.map((item) => {
                return (
                  <Link href={`${item.path}`} key={item.title}>
                    <a className={styles.nav__item}>
                      <span className={styles.item__image}>{item.icon}</span>
                      <h3 className={styles.item__title}>{item.title}</h3>
                    </a>
                  </Link>
                );
              })}

            </div>
          </div>

        </div>
      </motion.section>
      {isVisible && (
        <motion.div 
        className={styles.popup}
        initial={{y: 500}}
        animate={{ y: 0}}
        exit={{y:500, duration: 1 }}
        transition={{duration: 1, ease: "easeInOut"}}
        >
          <div className={styles.popup__container}>
            <div className={styles.popup__inner}>
              <button 
                className={styles.popup__close_button}
                onClick={() => setIsVisible(!isVisible)}
                >
                  <Image
                  src={arriw__down}
                  width={45}
                  height={40}
                  />
                </button>
              <h3 className={styles.popup__title}>
                Solicită prezentarea
                <br />
                <span className={styles.popup__title_mark}>
                  NEWTON PARK
                </span>{" "}
                PDF
              </h3>
              <form className={styles.popup__form}>
                <input type="email" placeholder="Adresa de email" />
                <input type="tel" placeholder="Numărul de telefon" />
                <button type="submit">Solicită prezentarea</button>
              </form>
              <p className={styles.popup__text}>Sau contactează-ne:</p>
              <PopUpMessenger/>
            </div>
          </div>
        </motion.div>
      )}
    </>
  );
}
