import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.scss";
import { motion } from "framer-motion";
import gsap from "gsap";

import logo from "../public/static/home/logo.svg";
import market from "../public/static/home/supermarket.svg";
import restaurant from "../public/static/home/restaurant-icon.svg";
import food from "../public/static/home/fast-food.svg";
import b__retail from "../public/static/home/big-retail.svg";
import home__decor from "../public/static/home/home-decor.svg";
import m__retail from "../public/static/home/medium-retail.svg";

const nav__items = [
  { id: 1, title: "supermarket", image: market, path: "market" },
  { id: 2, title: "restaurant", image: restaurant, path: "restaurant" },
  { id: 3, title: "fast-food", image: food, path: "fast-food" },
  { id: 4, title: "big retail", image: b__retail, path: "big-retail" },
  { id: 5, title: "home decor", image: home__decor, path: "home-decor" },
  { id: 6, title: "medium retail", image: m__retail, path: "medium-retail" },
];

export default function Home() {
  // const home__ref = React.useRef(null);

  // React.useEffect(() => {
  //   gsap.from(home__ref.current, {
  //     // opacity: 1,
  //     duration: 3,
  //     delay: 3,
  //   });
  // }, [home__ref]);

  React;
  return (
    <>
      <Head>
        <title>Newton Park</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.section
        className={styles.home}
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        transition={{ duration: 0.3 }}
      >
        <div className={styles.home__bg}>
          <div className={styles.home__shadow}></div>

          <header className={styles.header}>
            <div className={styles.header__wrapper}>
              <div className={styles.logo}>
                <Image src={logo} height={57} width={109} />
              </div>
            </div>
          </header>
        </div>
        <div className={styles.container}>
          <div className={styles.inner}>
            <div className={styles.content}>
              <h1 className={styles.title}>SPAȚII COMERCIALE </h1>
              <p className={styles.NP__decor_title}>NEWTON PARK</p>
              <p className={styles.subtitle}>Proeminente și fără replică</p>
            </div>

            <div className={styles.form__inner}>
              <h2 className={styles.form__title}>
                Solicită prezentarea
                <br />
                <span className={styles.NP__decor_form}>NEWTON PARK</span> PDF
              </h2>
              <form className={styles.form}>
                <input type="email" placeholder="Adresa de email" />
                <input type="tel" placeholder="Numărul de telefon" />
                <button className={styles.form__button}>
                  Solicită prezentarea
                </button>
              </form>
            </div>
          </div>
          <div className={styles.nav__inner}>
            <div className={styles.nav__items}>
              {nav__items.map((item) => {
                return (
                  <Link href={`/${item.path}/`} key={item.title}>
                    <a className={styles.nav__item} key={item.id}>
                      <p className={styles.item__image}>
                        <Image
                          src={item.image}
                          height={84}
                          width={100}
                          priority
                          alt={item.title}
                        />
                      </p>
                      <h3 className={styles.item__title}>{item.title}</h3>
                    </a>
                  </Link>
                );
              })}
            </div>
          </div>
        </div>
      </motion.section>
    </>
  );
}
